import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

type style = {
  navClassName: string;
  LinkClassName: string;
};
const navStyle: style = {
  navClassName: "p-8 flex gap-2.5 justify-center",
  LinkClassName: "text-xl py-1.5 px-2.5 bg-orange-300 text-teal-600",
};

export const metadata: Metadata = {
  title: "Daily-Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className={navStyle.navClassName}>
          <Link
            className={navStyle.LinkClassName}
            href="/SSG"
          >
            SSG
          </Link>
          <Link
            className={navStyle.LinkClassName}
            href="/ISR"
          >
            ISR
          </Link>
          <Link
            className={navStyle.LinkClassName}
            href="/SSR"
          >
            SSR
          </Link>
          <Link
            className={navStyle.LinkClassName}
            href="/CSR"
          >
            CSR
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
