import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { navStyle } from "@/app/style";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Daily-Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className={navStyle.navClassName}>
          <Link
            className={navStyle.LinkClassName}
            href="/"
          >
            SSG
          </Link>
          <Link
            className={navStyle.LinkClassName}
            href="/ISR"
          >
            ISR
          </Link>
          <Link
            className={navStyle.LinkClassName}
            href="/SSR"
          >
            SSR
          </Link>
          <Link
            className={navStyle.LinkClassName}
            href="/CSR"
          >
            CSR
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
